//! SMT objects that can be evaluated in a model to return a concrete SMT type.

use std::{
    cell::RefCell,
    fmt::{self, Display},
    str::FromStr,
};

use num::{BigInt, BigRational};
use thiserror::Error;
use z3::{
    ast::{Ast, Bool, Dynamic, Int, Real},
    FuncDecl, FuncInterp, Model,
};

use crate::{array::ConcreteArrayValue, list::ConcreteList};

/// Whether the model is guaranteed to be consistent with the constraints added
/// to the solver or not. When the SMT solver returns `SAT`, the model is
/// consistent (modulo bugs), but when the solver returns `UNKNOWN` we can also
/// obtain a model from the solver - just without any guarantees that it's
/// actually a model for the problem we asked for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModelConsistency {
    /// When the SMT solver returns [`z3::SatResult::Sat`], then the model is
    /// guaranteed to be consistent with the constraints.
    Consistent,
    /// When the SMT solver returns [`z3::SatResult::Unknown`], then we can also
    /// sometimes obtain a model from the solver, but it's not guaranteed to be
    /// consistent with the constraints. This model can be useful to localize
    /// errors with slicing - we just don't have *any* theoretical guarantees
    /// anymore.
    Unknown,
}

/// A [`z3::Model`] which keeps track of the accessed constants. This is useful
/// to later print those constants which were not accessed by any of the
/// [`SmtEval`] implementations (e.g. stuff generated by Z3 we don't know
/// about). This way, we can print the whole model and pretty-print everything
/// we know, and then print the rest of the assignments in the model as well.
#[derive(Debug)]
pub struct InstrumentedModel<'ctx> {
    consistency: ModelConsistency,
    model: Model<'ctx>,
    accessed_decls: RefCell<AccessedDecls<'ctx>>,
}

impl<'ctx> InstrumentedModel<'ctx> {
    pub fn new(consistency: ModelConsistency, model: Model<'ctx>) -> Self {
        InstrumentedModel {
            consistency,
            model,
            accessed_decls: Default::default(),
        }
    }

    /// Get the consistency of this model.
    pub fn consistency(&self) -> ModelConsistency {
        self.consistency
    }

    /// Execute this function "atomically" on this model, rolling back any
    /// changes to the list of visited decls/exprs if the function fails with an
    /// error.
    pub fn atomically<T>(
        &self,
        f: impl FnOnce() -> Result<T, SmtEvalError>,
    ) -> Result<T, SmtEvalError> {
        let accessed_decls = self.accessed_decls.borrow().clone();
        let res = f();
        if res.is_err() {
            *self.accessed_decls.borrow_mut() = accessed_decls;
        }
        res
    }

    /// Evaluate the given ast node in this model. `model_completion` indicates
    /// whether the node should be assigned a value even if it is not present in
    /// the model.
    pub fn eval_ast<T: Ast<'ctx>>(&self, ast: &T, model_completion: bool) -> Option<T> {
        self.accessed_decls.borrow_mut().mark_expr(ast);
        let res = self.model.eval(ast, model_completion)?;
        Some(res)
    }

    /// Get the function interpretation for this `f`.
    pub fn get_func_interp(&self, f: &FuncDecl<'ctx>) -> Option<FuncInterp<'ctx>> {
        self.accessed_decls.borrow_mut().mark_func_decl(f);
        self.model.get_func_interp(f)
    }

    /// Iterate over all function declarations that were not accessed using
    /// `eval` so far.
    pub fn iter_unaccessed(&self) -> impl Iterator<Item = FuncDecl<'ctx>> + '_ {
        self.model
            .iter()
            .filter(|decl| !self.accessed_decls.borrow().is_func_decl_accessed(decl))
    }

    /// Reset the internally tracked accessed declarations and expressions.
    pub fn reset_accessed(&mut self) {
        self.accessed_decls = Default::default();
    }

    pub fn into_model(self) -> Model<'ctx> {
        self.model
    }
}

/// The [`Display`] implementation simply defers to the underlying
/// [`z3::Model`]'s implementation.
impl Display for InstrumentedModel<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_fmt(format_args!("{}", &self.model))
    }
}

#[derive(Error, Debug, Clone)]
pub enum SmtEvalError {
    #[error("solver failed to evaluate a value")]
    EvalError,
    #[error("could not parse value from solver")]
    ParseError,
}

/// Keeps track of the accessed declarations during evaluation of the model.
///
/// This struct is cheap to clone because it uses immutable data structures.
#[derive(Debug, Default, Clone)]
struct AccessedDecls<'ctx> {
    // TODO: turn this into a HashSet of FuncDecls when the type implements Hash
    accessed_decls: im_rc::HashSet<String>,
    accessed_exprs: im_rc::HashSet<Dynamic<'ctx>>,
}

impl<'ctx> AccessedDecls<'ctx> {
    pub fn mark_func_decl(&mut self, f: &FuncDecl<'ctx>) {
        self.accessed_decls.insert(f.name());
    }

    pub fn is_func_decl_accessed(&self, f: &FuncDecl<'ctx>) -> bool {
        self.accessed_decls.contains(&f.name())
    }

    pub fn mark_expr<T: Ast<'ctx>>(&mut self, ast: &T) {
        if ast.is_const() {
            self.accessed_decls.insert(ast.decl().name());
        } else if ast.is_app() {
            for child in ast.children() {
                // some Z3 expressions might be extremely big because they
                // contain big expressions repeatedly. so the following check is
                // necessary to avoid walking through these expressions for a
                // very long time.
                let prev = self.accessed_exprs.insert(child.clone());
                if prev.is_some() {
                    continue;
                }
                self.mark_expr(&child);
            }
        }
    }
}

/// SMT objects that can be evaluated to a concrete value given a model.
pub trait SmtEval<'ctx> {
    type Value;

    // TODO: pass a model completion option?
    fn eval(&self, model: &InstrumentedModel<'ctx>) -> Result<Self::Value, SmtEvalError>;
}

impl<'ctx> SmtEval<'ctx> for Bool<'ctx> {
    type Value = bool;

    fn eval(&self, model: &InstrumentedModel<'ctx>) -> Result<bool, SmtEvalError> {
        Ok(model
            .eval_ast(self, false)
            .ok_or(SmtEvalError::EvalError)?
            .as_bool()
            .unwrap_or(true))
    }
}

impl<'ctx> SmtEval<'ctx> for Int<'ctx> {
    type Value = BigInt;

    fn eval(&self, model: &InstrumentedModel<'ctx>) -> Result<BigInt, SmtEvalError> {
        let res = model.eval_ast(self, true).ok_or(SmtEvalError::EvalError)?;
        if let Some(value) = res.as_i64() {
            return Ok(BigInt::from(value));
        }
        parse_z3_integer(&format!("{res:?}"))
    }
}

/// Parse a Z3 real value from its debug string representation.
///
/// Z3 can produce several formats when `as_real()` doesn't fit in i64:
///   `(/ num.0 denom.0)`, `(- (/ num.0 denom.0))`, `(/ (- num.0) denom.0)`
fn parse_z3_real_string(s: &str) -> Result<BigRational, SmtEvalError> {
    let s = s.trim();

    // Strip outer "(- ...)" negation wrapper
    if let Some(inner) = s.strip_prefix("(- ").and_then(|t| t.strip_suffix(')')) {
        return parse_z3_real_string(inner).map(|r| -r);
    }

    // Parse "(/ num denom)" where num/denom may themselves be "(- n.0)"
    if let Some(body) = s.strip_prefix("(/ ").and_then(|t| t.strip_suffix(')')) {
        let (num_str, den_str) = split_two_sexpr(body).ok_or(SmtEvalError::ParseError)?;
        let numerator = parse_z3_integer(num_str.trim())?;
        let denominator = parse_z3_integer(den_str.trim())?;
        return Ok(BigRational::new(numerator, denominator));
    }

    // Plain integer (with or without ".0" suffix)
    parse_z3_integer(s).map(BigRational::from)
}

/// Parse a Z3 integer atom: `"42.0"`, `"42"`, or `"(- 42.0)"`.
fn parse_z3_integer(s: &str) -> Result<BigInt, SmtEvalError> {
    let s = s.trim();
    if let Some(inner) = s.strip_prefix("(- ").and_then(|t| t.strip_suffix(')')) {
        return parse_z3_integer(inner).map(|n| -n);
    }
    let s = s.trim_end_matches(".0");
    BigInt::from_str(s).map_err(|_| SmtEvalError::ParseError)
}

/// Split a body string into exactly two s-expressions (atoms or parenthesised).
fn split_two_sexpr(s: &str) -> Option<(&str, &str)> {
    let s = s.trim();
    let (first_end, second_start) = if s.starts_with('(') {
        let mut depth = 0usize;
        let mut end = 0;
        for (i, c) in s.char_indices() {
            match c {
                '(' => depth += 1,
                ')' => {
                    depth -= 1;
                    if depth == 0 {
                        end = i + 1;
                        break;
                    }
                }
                _ => {}
            }
        }
        (end, end)
    } else {
        let end = s.find(|c: char| c.is_ascii_whitespace()).unwrap_or(s.len());
        (end, end)
    };
    let first = &s[..first_end];
    let rest = s[second_start..].trim_start();
    if first.is_empty() || rest.is_empty() {
        return None;
    }
    Some((first, rest))
}

/// Evaluate a raw SMT value for display.
///
/// This only recognizes z3rro's built-in list and array encodings and
/// otherwise falls back to Z3's default rendering.
impl<'ctx> SmtEval<'ctx> for Dynamic<'ctx> {
    type Value = String;

    fn eval(&self, model: &InstrumentedModel<'ctx>) -> Result<Self::Value, SmtEvalError> {
        let value = model.eval_ast(self, true).ok_or(SmtEvalError::EvalError)?;
        if let Ok(value) = ConcreteList::from_dynamic(&value) {
            return Ok(value.to_string());
        }
        if let Some(value) = ConcreteArrayValue::from_dynamic(&value) {
            return Ok(value.to_string());
        }
        Ok(value.to_string())
    }
}

impl<'ctx> SmtEval<'ctx> for Real<'ctx> {
    type Value = BigRational;

    fn eval(&self, model: &InstrumentedModel<'ctx>) -> Result<Self::Value, SmtEvalError> {
        let res = model.eval_ast(self, true).ok_or(SmtEvalError::EvalError)?;

        // The .as_real() method only returns a pair of i64 values. If the
        // results don't fit in these types, we start some funky string parsing.
        if let Some((num, den)) = res.as_real() {
            Ok(BigRational::new(num.into(), den.into()))
        } else {
            // Parse Z3 real string representations. Possible formats:
            //   "(/ num.0 denom.0)"
            //   "(- (/ num.0 denom.0))"
            //   "(/ (- num.0) denom.0)"
            parse_z3_real_string(&format!("{res:?}"))
        }
    }
}
