# Build a VSIX bundle for the VScode extension and add it to GitHub release
name: Build VSIX

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
      version:
        required: true
        type: string
      is_prerelease:
        required: true
        type: boolean

env:
  EXTENSION_DIRECTORY: ./vscode-ext

jobs:
  build-vsix:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git_ref }}
  
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: vscode-ext/yarn.lock
    
      - name: Install Yarn dependencies
        working-directory: ${{ env.EXTENSION_DIRECTORY }}
        run: yarn install --frozen-lockfile
      
      - name: Set package flags (for pre-release)
        if: ${{ inputs.is_prerelease }}
        shell: bash
        run: |
          echo "PACKAGE_EXTRA_FLAGS=--pre-release" >> $GITHUB_ENV
  
      - name: Package the extension
        working-directory: ${{ env.EXTENSION_DIRECTORY }}
        run: yarn package --out caesar-${{ inputs.version }}.vsix $PACKAGE_EXTRA_FLAGS

      - name: Upload Release Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.git_ref }}
          # Also need to specify 'draft' again, so that the action finds the correct existing (draft) release
          draft: ${{ !inputs.is_prerelease }}
          files: |
            ${{env.EXTENSION_DIRECTORY}}/caesar-${{ inputs.version }}.vsix
  
